// <auto-generated />
namespace Sentiment.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addstate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addstate));
        
        string IMigrationMetadata.Id
        {
            get { return "201910131300082_addstate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
